# Generated by Django 3.2.3 on 2021-11-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsfas_tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
