# Generated by Django 3.2.3 on 2021-11-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsfas_tracking', '0004_authuser_djangosession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
