# Generated by Django 3.2.3 on 2021-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReg',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('join_time', models.CharField(max_length=45)),
                ('leave_time', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'attendance_reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('first_fame', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('job_title', models.CharField(max_length=45)),
                ('phone_num', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerLogin',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'lecturer_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('module_namel', models.CharField(max_length=40, unique=True)),
                ('course_code', models.CharField(max_length=7)),
                ('lecturer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsfasEmpl',
            fields=[
                ('nsfas_emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('first_fame', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('job_title', models.CharField(max_length=45)),
                ('phone_num', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'nsfas_empl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsfasHasStudent',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('nsfas_emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'nsfas_has_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsfasLogin',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'nsfas_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_link', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('module_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('stud_email', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('nsfas_status', models.IntegerField()),
                ('course_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentHasModule',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('module_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'student_has_module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('re_password', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'student_login',
                'managed': False,
            },
        ),
    ]
